# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

trigger:
- master
pool:
  vmImage: 'Ubuntu 16.04'
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*SimpleAzureFunctionApp.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'build stage v1'
  inputs:
    command: 'build'
    projects: '**/*SimpleAzureFunctionApp.csproj'
    arguments: 'Build stage'